import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import Container from "../components/Container";
import Header from "../components/Header";

const Test = styled.h1`
  color: blue;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Airdrop checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>index + 1</div>
    </div>
  );
}
