import Head from "next/head";
import Header from "../components/Header";
import Container from "../components/Container";
//import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Airdrop checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Container>
          <div className="mx-auto w-full space-y-10 mt-16">
            <p className="uppercase text-center font-bold">
              welcome to airdrop checker
            </p>
            <h1 className="md:text-7xl mx-auto max-w-xl text-center font-bold">
              Never miss airdrops.
            </h1>
            <p className="text-center max-w-2xl mx-auto">
              Ernify is a software which find and alert you when you are avaible
              for an airdrop. apps and services, built for a decentralized
              future.
            </p>
          </div>
        </Container>
      </div>

      <div>index + 1</div>
    </div>
  );
}
